### ISSUE TITLE
Errors unless logged in

### ISSUE THREAD

**Issue by richardcornish** [krisfields/django-baker#5]
You get errors unless you're logged in. Without an auth app, that likely means from the admin. I think it's worth mentioning in the README.

**Comment by krisfields** [comment]
Ah, you're right.  I added the login_required decorator to all the CreateView, UpdateView, and DeleteView classes because I've never personally built an app where you could create, update or delete without being logged in.  But I can definitely imagine scenarios where that would be the case.  I think ideally I'd make this decorator optional.  Until then, I've updated the README per your recommendation.
